### ISSUE TITLE
infrastructure agent update

### ISSUE THREAD

**Issue by srisailab** [newrelic/infrastructure-agent-chef#45]
We are upgrading the infrastructure from version X to Version Y

After editing the version in default attributes , should the agents on the individual servers be restarted manually ?

**Comment by smith** [comment]
The recipe will only a trigger a restart of the service if the contents of the newrelic.yml changes, but installing a new version of the package might restart the service automatically.

I'm leaving this open because the correct thing for the recipe to do is probably to have the recipe explicitly trigger a restart.

Thanks!

**Comment by alejandrodnm** [comment]
Sorry, for the super late response #shame. 

An update should restart the service automatically, unless you have explicitly in a cookbook something like `newrelic-infra` should be stopped. It's the same as an upgrade through yum, apt or zypper, the service stops, the old version removed, the new one added and service started. All of that is actually handled by `rpm` and `dpkg`.

I'm closing the issue, but feel free to ask more questions or reopen it.

Once again, sorry for the late response.
